[package]
name = "screeps-starter-rust"
version = "0.0.0"
authors = []

[dependencies]
stdweb = "0.4"
log = "0.4"
fern = "0.5"
screeps-game-api = { version = "0.4", path = "../screeps-api/screeps-game-api" }

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
